src/Entity/Offers.php
<?php

namespace App\Entity;

use App\Repository\OffersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OffersRepository::class)
 */
class Offers
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180)
     */
    private $offer_name;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToMany(targetEntity=Skills::class)
     */
    private $skill;

    public function __construct()
    {
        $this->skill = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOfferName(): ?string
    {
        return $this->offer_name;
    }

    public function setOfferName(string $offer_name): self
    {
        $this->offer_name = $offer_name;

        return $this;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Skills[]
     */
    public function getSkill(): Collection
    {
        return $this->skill;
    }

    public function addSkill(Skills $skill): self
    {
        if (!$this->skill->contains($skill)) {
            $this->skill[] = $skill;
        }

        return $this;
    }

    public function removeSkill(Skills $skill): self
    {
        $this->skill->removeElement($skill);

        return $this;
    }
}

src/Form/OffersType.php
<?php

namespace App\Form;

use App\Entity\Offers;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OffersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('offer_name')
            ->add('user')
            ->add('skill')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Offers::class,
        ]);
    }
}

src/Controller/OffersController.php
<?php

namespace App\Controller;

use App\Entity\Offers;
use App\Form\OffersType;
use App\Repository\OffersRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/offers")
 */
class OffersController extends AbstractController
{
    /**
     * @Route("/", name="offers_index", methods={"GET"})
     */
    public function index(OffersRepository $offersRepository): Response
    {
        return $this->render('offers/index.html.twig', [
            'offers' => $offersRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="offers_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $offer = new Offers();
        $form = $this->createForm(OffersType::class, $offer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($offer);
            $entityManager->flush();

            return $this->redirectToRoute('offers_index');
        }

        return $this->render('offers/new.html.twig', [
            'offer' => $offer,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="offers_show", methods={"GET"})
     */
    public function show(Offers $offer): Response
    {
        return $this->render('offers/show.html.twig', [
            'offer' => $offer,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="offers_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Offers $offer): Response
    {
        $form = $this->createForm(OffersType::class, $offer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('offers_index');
        }

        return $this->render('offers/edit.html.twig', [
            'offer' => $offer,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="offers_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Offers $offer): Response
    {
        if ($this->isCsrfTokenValid('delete'.$offer->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($offer);
            $entityManager->flush();
        }

        return $this->redirectToRoute('offers_index');
    }
}

templates/offers/_delete_form.html.twig
<form method="post" action="{{ path('offers_delete', {'id': offer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ offer.id) }}">
    <button class="btn">Delete</button>
</form>

templates/offers/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/offers/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Offers{% endblock %}

{% block body %}
    <h1>Edit Offers</h1>

    {{ include('offers/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('offers_index') }}">back to list</a>

    {{ include('offers/_delete_form.html.twig') }}
{% endblock %}

templates/offers/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Offers index{% endblock %}

{% block body %}
    <h1>Offers index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Offer_name</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for offer in offers %}
            <tr>
                <td>{{ offer.id }}</td>
                <td>{{ offer.offerName }}</td>
                <td>
                    <a href="{{ path('offers_show', {'id': offer.id}) }}">show</a>
                    <a href="{{ path('offers_edit', {'id': offer.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('offers_new') }}">Create new</a>
{% endblock %}

templates/offers/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Offers{% endblock %}

{% block body %}
    <h1>Create new Offers</h1>

    {{ include('offers/_form.html.twig') }}

    <a href="{{ path('offers_index') }}">back to list</a>
{% endblock %}

templates/offers/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Offers{% endblock %}

{% block body %}
    <h1>Offers</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ offer.id }}</td>
            </tr>
            <tr>
                <th>Offer_name</th>
                <td>{{ offer.offerName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('offers_index') }}">back to list</a>

    <a href="{{ path('offers_edit', {'id': offer.id}) }}">edit</a>

    {{ include('offers/_delete_form.html.twig') }}
{% endblock %}