src/Entity/Skills.php
<?php

namespace App\Entity;

use App\Repository\SkillsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SkillsRepository::class)
 */
class Skills
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180)
     */
    private $skill_name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSkillName(): ?string
    {
        return $this->skill_name;
    }

    public function setSkillName(string $skill_name): self
    {
        $this->skill_name = $skill_name;

        return $this;
    }

    public function __toString()
    {
        return $this->skill_name;
    }
}

src/Form/SkillsType.php
<?php

namespace App\Form;

use App\Entity\Skills;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SkillsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('skill_name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Skills::class,
        ]);
    }
}

src/Controller/SkillsController.php
<?php

namespace App\Controller;

use App\Entity\Skills;
use App\Form\SkillsType;
use App\Repository\SkillsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/skills")
 */
class SkillsController extends AbstractController
{
    /**
     * @Route("/", name="skills_index", methods={"GET"})
     */
    public function index(SkillsRepository $skillsRepository): Response
    {
        return $this->render('skills/index.html.twig', [
            'skills' => $skillsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="skills_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $skill = new Skills();
        $form = $this->createForm(SkillsType::class, $skill);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($skill);
            $entityManager->flush();

            return $this->redirectToRoute('skills_index');
        }

        return $this->render('skills/new.html.twig', [
            'skill' => $skill,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="skills_show", methods={"GET"})
     */
    public function show(Skills $skill): Response
    {
        return $this->render('skills/show.html.twig', [
            'skill' => $skill,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="skills_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Skills $skill): Response
    {
        $form = $this->createForm(SkillsType::class, $skill);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('skills_index');
        }

        return $this->render('skills/edit.html.twig', [
            'skill' => $skill,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="skills_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Skills $skill): Response
    {
        if ($this->isCsrfTokenValid('delete'.$skill->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($skill);
            $entityManager->flush();
        }

        return $this->redirectToRoute('skills_index');
    }
}

templates/skills/_delete_form.html.twig
<form method="post" action="{{ path('skills_delete', {'id': skill.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ skill.id) }}">
    <button class="btn">Delete</button>
</form>

templates/skills/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/skills/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Skills{% endblock %}

{% block body %}
    <h1>Edit Skills</h1>

    {{ include('skills/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('skills_index') }}">back to list</a>

    {{ include('skills/_delete_form.html.twig') }}
{% endblock %}

templates/skills/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Skills index{% endblock %}

{% block body %}
    <h1>Skills index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Skill_name</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for skill in skills %}
            <tr>
                <td>{{ skill.id }}</td>
                <td>{{ skill.skillName }}</td>
                <td>
                    <a href="{{ path('skills_show', {'id': skill.id}) }}">show</a>
                    <a href="{{ path('skills_edit', {'id': skill.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('skills_new') }}">Create new</a>
{% endblock %}

templates/skills/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Skills{% endblock %}

{% block body %}
    <h1>Create new Skills</h1>

    {{ include('skills/_form.html.twig') }}

    <a href="{{ path('skills_index') }}">back to list</a>
{% endblock %}

templates/skills/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Skills{% endblock %}

{% block body %}
    <h1>Skills</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ skill.id }}</td>
            </tr>
            <tr>
                <th>Skill_name</th>
                <td>{{ skill.skillName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('skills_index') }}">back to list</a>

    <a href="{{ path('skills_edit', {'id': skill.id}) }}">edit</a>

    {{ include('skills/_delete_form.html.twig') }}
{% endblock %}